// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Fetch from "bs-fetch/src/Fetch.js";

function get(url, decode) {
  return fetch(url, Fetch.RequestInit[/* make */0](/* Get */0, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Curry._1(decode, json));
              }));
}

var Fetch$1 = /* module */[/* get */get];

function latest(decode) {
  return get("/api/jobs/latest", decode);
}

function jobs(decode) {
  return get("/api/jobs", decode);
}

function job(id, decode) {
  return get("/api/job/" + (String(id) + ""), decode);
}

var Jobs = /* module */[
  /* latest */latest,
  /* jobs */jobs,
  /* job */job
];

export {
  Fetch$1 as Fetch,
  Jobs ,
  
}
/* No side effect */
