// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Fetch from "bs-fetch/src/Fetch.js";
import * as Jobs_bs$Frontend from "../types/jobs_bs.bs.js";
import * as Atdgen_codec_runtime from "@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js";

function get(url, decode) {
  return fetch(url, Fetch.RequestInit[/* make */0](/* Get */0, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Curry._1(decode, json));
              }));
}

var Fetch$1 = /* module */[/* get */get];

function latest(decode) {
  return get("/api/jobs/latest", decode);
}

function jobs(url) {
  var partial_arg = Atdgen_codec_runtime.Decode[/* decode */1];
  return get(url, (function (param) {
                return partial_arg(Jobs_bs$Frontend.read_latestJobs, param);
              }));
}

function job(id, decode) {
  return get("/api/job/" + (String(id) + ""), decode);
}

var Jobs = /* module */[
  /* latest */latest,
  /* jobs */jobs,
  /* job */job
];

export {
  Fetch$1 as Fetch,
  Jobs ,
  
}
/* Jobs_bs-Frontend Not a pure module */
