// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var list = Belt_List.toArray;

var RR = /* module */[
  /* statelessComponent */ReasonReact.statelessComponent,
  /* statelessComponentWithRetainedProps */ReasonReact.statelessComponentWithRetainedProps,
  /* reducerComponent */ReasonReact.reducerComponent,
  /* reducerComponentWithRetainedProps */ReasonReact.reducerComponentWithRetainedProps,
  /* element */ReasonReact.element,
  /* wrapReasonForJs */ReasonReact.wrapReasonForJs,
  /* createDomElement */ReasonReact.createDomElement,
  /* wrapJsForReason */ReasonReact.wrapJsForReason,
  /* Router */ReasonReact.Router,
  /* list */list
];

function s(prim) {
  return prim;
}

function wrap(urlPath) {
  if (urlPath && urlPath[0] === "jobs") {
    return /* Jobs */1;
  } else {
    return /* Home */0;
  }
}

var Router = /* module */[/* wrap */wrap];

export {
  RR ,
  s ,
  Router ,
  
}
/* ReasonReact Not a pure module */
