// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Job$Frontend from "./Pages/Job.bs.js";
import * as Home$Frontend from "./Pages/Home.bs.js";
import * as Jobs$Frontend from "./Pages/Jobs.bs.js";
import * as Footer$Frontend from "./components/Footer.bs.js";
import * as Header$Frontend from "./components/Header.bs.js";
import * as NewJob$Frontend from "./Pages/NewJob.bs.js";
import * as Prelude$Frontend from "./helpers/Prelude.bs.js";
import * as NotFound$Frontend from "./Pages/NotFound.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var route = Prelude$Frontend.Router[/* parseUrl */0](url);
  var tmp;
  if (typeof route === "number") {
    switch (route) {
      case 0 : 
          tmp = React.createElement(Home$Frontend.make, { });
          break;
      case 1 : 
          tmp = React.createElement(Jobs$Frontend.make, { });
          break;
      case 2 : 
          tmp = React.createElement(NewJob$Frontend.make, { });
          break;
      case 3 : 
          tmp = React.createElement(NotFound$Frontend.make, { });
          break;
      
    }
  } else {
    tmp = React.createElement(Job$Frontend.make, {
          id: route[0]
        });
  }
  return React.createElement("div", {
              className: "page"
            }, React.createElement("div", {
                  className: "flex-fill"
                }, React.createElement(Header$Frontend.make, { }), React.createElement("div", {
                      className: "my-3 my-md-5"
                    }, tmp)), React.createElement(Footer$Frontend.make, { }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
