// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Home$Tripdeer from "./Pages/Home.bs.js";
import * as Jobs$Tripdeer from "./Pages/Jobs.bs.js";
import * as Footer$Tripdeer from "./components/Footer.bs.js";
import * as Header$Tripdeer from "./components/Header.bs.js";
import * as Prelude$Tripdeer from "./helpers/Prelude.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = React.useState((function () {
          return /* Home */0;
        }));
  var setRoute = match[1];
  React.useEffect((function () {
          Curry._1(setRoute, (function (param) {
                  return Prelude$Tripdeer.Router[/* wrap */0](url[/* path */0]);
                }));
          return undefined;
        }), /* array */[url[/* path */0]]);
  return React.createElement("div", {
              className: "page"
            }, React.createElement("div", {
                  className: "flex-fill"
                }, React.createElement(Header$Tripdeer.make, { }), React.createElement("div", {
                      className: "my-3 my-md-5"
                    }, match[0] ? React.createElement(Jobs$Tripdeer.make, { }) : React.createElement(Home$Tripdeer.make, { }))), React.createElement(Footer$Tripdeer.make, { }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
