// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App$Tripdeer from "./App.bs.js";

((require("./assets/css/dashboard.css")));

ReactDOMRe.renderToElementWithId(React.createElement(App$Tripdeer.make, { }), "root");

export {
  
}
/*  Not a pure module */
