// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";

function FormErrorMsg(Props) {
  var type_ = Props.type_;
  if (type_ !== undefined) {
    var match = type_;
    if (match.tag) {
      return React.createElement("p", {
                  className: Cn.make(/* :: */[
                        "text-danger",
                        /* [] */0
                      ])
                }, Prelude$Frontend.s(match[0]));
    } else {
      return null;
    }
  } else {
    return null;
  }
}

var make = FormErrorMsg;

export {
  make ,
  
}
/* react Not a pure module */
