// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Prelude$Tripdeer from "../helpers/Prelude.bs.js";

function Home(Props) {
  return React.createElement("div", {
              className: "container"
            }, React.createElement("div", {
                  className: "page-header"
                }, React.createElement("h1", {
                      className: "page-title"
                    }, Prelude$Tripdeer.s("Home"))), React.createElement("div", {
                  className: "row row-cards row-deck"
                }, React.createElement("div", {
                      className: "col-12"
                    }, React.createElement("div", {
                          className: "card"
                        }, Prelude$Tripdeer.s("Home page")))));
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
