// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Api$Tripdeer from "../helpers/Api.bs.js";
import * as Jobs_bs$Tripdeer from "../types/jobs_bs.bs.js";
import * as Prelude$Tripdeer from "../helpers/Prelude.bs.js";
import * as Home_Css$Tripdeer from "./Home_Css.bs.js";
import * as Atdgen_codec_runtime from "@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js";

function Home(Props) {
  var match = React.useState((function () {
          return /* Loading */0;
        }));
  var setJobs = match[1];
  var jobs = match[0];
  React.useEffect((function () {
          var partial_arg = Atdgen_codec_runtime.Decode[/* decode */1];
          Api$Tripdeer.Jobs[/* latest */0]((function (param) {
                    return partial_arg(Jobs_bs$Tripdeer.read_jobs, param);
                  })).then((function (res) {
                  return Promise.resolve(Curry._1(setJobs, (function (param) {
                                    return /* Loaded */[res];
                                  })));
                }));
          return undefined;
        }), ([]));
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: Home_Css$Tripdeer.container
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: Home_Css$Tripdeer.header
                        }, React.createElement("h1", {
                              className: Home_Css$Tripdeer.title
                            }, Prelude$Tripdeer.s("Parents friendly jobs")), React.createElement("h3", {
                              className: Home_Css$Tripdeer.subTitle
                            }, Prelude$Tripdeer.s("Parental job is the largest parents friendly work community in the\n          world. We aggregate jobs from everywhere so you don't have to search around everywhere.")), React.createElement("button", {
                              className: Home_Css$Tripdeer.button
                            }, Prelude$Tripdeer.s("Post a job for free!"))))), React.createElement("div", {
                  className: Cn.make(/* :: */[
                        "container",
                        /* :: */[
                          Home_Css$Tripdeer.jobsList,
                          /* [] */0
                        ]
                      ])
                }, jobs ? React.createElement("ul", undefined, Prelude$Tripdeer.RR[/* list */9](Belt_List.mapWithIndex(jobs[0], (function (index, param) {
                                  return React.createElement("li", {
                                              key: String(index),
                                              className: Home_Css$Tripdeer.job
                                            }, React.createElement("span", {
                                                  className: Home_Css$Tripdeer.avatar
                                                }), React.createElement("div", undefined, React.createElement("span", {
                                                      className: Home_Css$Tripdeer.company
                                                    }, Prelude$Tripdeer.s(param[/* company */0])), React.createElement("h3", {
                                                      className: Home_Css$Tripdeer.jobTitle
                                                    }, Prelude$Tripdeer.s(param[/* jobTitle */1])), React.createElement("cite", {
                                                      className: Home_Css$Tripdeer.category
                                                    }, React.createElement("span", undefined, Prelude$Tripdeer.s(param[/* jobCategories */7])))), React.createElement("div", {
                                                  className: Home_Css$Tripdeer.employmentType
                                                }, React.createElement("span", undefined, Prelude$Tripdeer.s(param[/* employmentType */4]))));
                                })))) : Prelude$Tripdeer.s("Loading...")));
}

var Css = 0;

var make = Home;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
