// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Api$Frontend from "../helpers/Api.bs.js";
import * as Avatar$Frontend from "../components/Avatar.bs.js";
import * as Jobs_bs$Frontend from "../types/jobs_bs.bs.js";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";
import * as Home_Css$Frontend from "./Home_Css.bs.js";
import * as Atdgen_codec_runtime from "@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js";

function Home(Props) {
  var match = React.useState((function () {
          return /* Loading */0;
        }));
  var setJobs = match[1];
  var jobs = match[0];
  React.useEffect((function () {
          var partial_arg = Atdgen_codec_runtime.Decode[/* decode */1];
          Api$Frontend.Jobs[/* latest */0]((function (param) {
                      return partial_arg(Jobs_bs$Frontend.read_latestJobs, param);
                    })).then((function (res) {
                    return Promise.resolve(Curry._1(setJobs, (function (param) {
                                      return /* Loaded */Block.__(0, [res]);
                                    })));
                  })).catch((function (err) {
                  return Promise.resolve(Curry._1(setJobs, (function (param) {
                                    return /* Error */Block.__(1, [err]);
                                  })));
                }));
          return undefined;
        }), ([]));
  var tmp;
  tmp = typeof jobs === "number" ? Prelude$Frontend.s("Loading...") : (
      jobs.tag ? Prelude$Frontend.s(jobs[0].toString()) : React.createElement("ul", undefined, Prelude$Frontend.RR[/* list */9](Belt_List.map(jobs[0], (function (param) {
                        var id = param[/* _id */0];
                        var company = param[/* company */1];
                        return React.createElement("li", {
                                    key: id,
                                    className: Home_Css$Frontend.job,
                                    onClick: (function ($$event) {
                                        return Prelude$Frontend.linkTo("/job/" + (String(id) + ""), $$event);
                                      })
                                  }, React.createElement(Avatar$Frontend.make, {
                                        className: Home_Css$Frontend.avatar,
                                        company: company
                                      }), React.createElement("div", undefined, React.createElement("span", {
                                            className: Home_Css$Frontend.company
                                          }, Prelude$Frontend.s(company)), React.createElement("h3", {
                                            className: Home_Css$Frontend.jobTitle
                                          }, Prelude$Frontend.s(param[/* jobTitle */2])), React.createElement("cite", {
                                            className: Home_Css$Frontend.category
                                          }, React.createElement("span", undefined, Prelude$Frontend.s(param[/* jobCategories */6])))), React.createElement("div", {
                                        className: Home_Css$Frontend.employmentType
                                      }, React.createElement("span", undefined, Prelude$Frontend.s(param[/* employmentType */3]))));
                      }))))
    );
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: Home_Css$Frontend.container
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: Home_Css$Frontend.header
                        }, React.createElement("h1", {
                              className: Home_Css$Frontend.title
                            }, Prelude$Frontend.s("Parents friendly jobs")), React.createElement("h3", {
                              className: Home_Css$Frontend.subTitle
                            }, Prelude$Frontend.s("Parental job is the largest parents friendly work community in the\n          world. We aggregate jobs from everywhere so you don't have to search around everywhere.")), React.createElement("button", {
                              className: Home_Css$Frontend.button
                            }, Prelude$Frontend.s("Post a job for free!"))))), React.createElement("div", {
                  className: Cn.make(/* :: */[
                        "container",
                        /* :: */[
                          Home_Css$Frontend.jobsList,
                          /* [] */0
                        ]
                      ])
                }, tmp));
}

var Css = 0;

var make = Home;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
