// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var hexRed = "ef4f00";

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* :: */[
        Emotion.borderBottom(/* `px */[
              25096,
              1
            ], /* solid */12956715, /* `hex */[
              5194459,
              "eee"
            ]),
        /* :: */[
          Emotion.paddingBottom(/* `px */[
                25096,
                60
              ]),
          /* [] */0
        ]
      ]
    ]);

var header = Emotion.css(undefined, /* :: */[
      Emotion.label("header"),
      /* :: */[
        Emotion.textAlign(/* center */98248149),
        /* [] */0
      ]
    ]);

var title = Emotion.css(undefined, /* :: */[
      Emotion.label("title"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              58
            ]),
        /* :: */[
          Emotion.padding2(/* `px */[
                25096,
                30
              ], /* `px */[
                25096,
                20
              ]),
          /* :: */[
            Emotion.marginBottom(/* zero */-789508312),
            /* :: */[
              Emotion.display(/* inlineBlock */-147785676),
              /* :: */[
                Emotion.color(/* `hex */[
                      5194459,
                      "333"
                    ]),
                /* :: */[
                  Emotion.fontWeight(700),
                  /* :: */[
                    Emotion.textTransform(/* uppercase */-415330030),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var subTitle = Emotion.css(undefined, /* :: */[
      Emotion.label("subTitle"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              18
            ]),
        /* :: */[
          Emotion.padding2(/* zero */-789508312, /* `px */[
                25096,
                20
              ]),
          /* :: */[
            Emotion.display(/* block */888960333),
            /* :: */[
              Emotion.margin3(/* zero */-789508312, /* auto */-1065951377, /* `px */[
                    25096,
                    30
                  ]),
              /* :: */[
                Emotion.textAlign(/* center */98248149),
                /* :: */[
                  Emotion.color(/* `hex */[
                        5194459,
                        "333"
                      ]),
                  /* :: */[
                    Emotion.fontWeight(400),
                    /* :: */[
                      Emotion.maxWidth(/* `px */[
                            25096,
                            920
                          ]),
                      /* :: */[
                        Emotion.lineHeight(/* `px */[
                              25096,
                              28
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var button = Emotion.css(undefined, /* :: */[
      Emotion.label("button"),
      /* :: */[
        Emotion.display(/* inlineBlock */-147785676),
        /* :: */[
          Emotion.borderStyle(/* none */-922086728),
          /* :: */[
            Emotion.padding2(/* `px */[
                  25096,
                  10
                ], /* `px */[
                  25096,
                  20
                ]),
            /* :: */[
              Emotion.backgroundColor(/* `hex */[
                    5194459,
                    hexRed
                  ]),
              /* :: */[
                Emotion.color(Emotion.Css[/* Color */11][/* white */145]),
                /* :: */[
                  Emotion.fontWeight(700),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var jobsList = Emotion.css(undefined, /* :: */[
      Emotion.label("jobsList"),
      /* :: */[
        Emotion.marginTop(/* `px */[
              25096,
              30
            ]),
        /* [] */0
      ]
    ]);

var job = Emotion.css(undefined, /* :: */[
      Emotion.label("job"),
      /* :: */[
        Emotion.backgroundColor(/* `rgba */[
              -878128972,
              /* tuple */[
                255,
                137,
                32,
                0.18
              ]
            ]),
        /* :: */[
          Emotion.margin(/* zero */-789508312),
          /* :: */[
            Emotion.listStyleType(/* none */-922086728),
            /* :: */[
              Emotion.padding(/* `px */[
                    25096,
                    10
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

export {
  hexRed ,
  container ,
  header ,
  title ,
  subTitle ,
  button ,
  jobsList ,
  job ,
  
}
/* container Not a pure module */
