// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Api$Frontend from "../helpers/Api.bs.js";
import * as Job_Css$Frontend from "./Job_Css.bs.js";
import * as Jobs_bs$Frontend from "../types/jobs_bs.bs.js";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";
import * as Atdgen_codec_runtime from "@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js";

function Job(Props) {
  var id = Props.id;
  var match = React.useState((function () {
          return /* Loading */0;
        }));
  var setJob = match[1];
  var job = match[0];
  React.useEffect((function () {
          var partial_arg = Atdgen_codec_runtime.Decode[/* decode */1];
          Api$Frontend.Jobs[/* job */1](id, (function (param) {
                      return partial_arg(Jobs_bs$Frontend.read_job, param);
                    })).then((function (res) {
                    return Promise.resolve(Curry._1(setJob, (function (param) {
                                      return /* Loaded */Block.__(0, [res]);
                                    })));
                  })).catch((function (err) {
                  return Promise.resolve(Curry._1(setJob, (function (param) {
                                    return /* Error */Block.__(1, [err]);
                                  })));
                }));
          return undefined;
        }), ([]));
  var tmp;
  if (typeof job === "number") {
    tmp = Prelude$Frontend.s("Loading...");
  } else if (job.tag) {
    tmp = Prelude$Frontend.s(job[0].toString());
  } else {
    var match$1 = job[0];
    var minExperience = match$1[/* minExperience */7];
    tmp = React.createElement("div", undefined, React.createElement("span", {
              className: Job_Css$Frontend.postDate
            }, Prelude$Frontend.s(match$1[/* postedOn */10])), React.createElement("h1", {
              className: Job_Css$Frontend.jobTitle
            }, Prelude$Frontend.s(match$1[/* jobTitle */2])), React.createElement("h4", {
              className: Job_Css$Frontend.companyName
            }, Prelude$Frontend.s(match$1[/* company */1])), React.createElement("p", {
              className: Job_Css$Frontend.tags
            }, React.createElement("span", {
                  className: Job_Css$Frontend.tag
                }, Prelude$Frontend.s(match$1[/* employmentType */5])), React.createElement("span", {
                  className: Job_Css$Frontend.tag
                }, Prelude$Frontend.s(match$1[/* seniority */6])), minExperience !== "" ? React.createElement("span", {
                    className: Job_Css$Frontend.tag
                  }, Prelude$Frontend.s(minExperience)) : null, React.createElement("span", {
                  className: Job_Css$Frontend.tag
                }, Prelude$Frontend.s(match$1[/* jobCategories */8]))), React.createElement("div", {
              className: Job_Css$Frontend.content,
              dangerouslySetInnerHTML: {
                __html: match$1[/* jobDescription */11]
              }
            }), React.createElement("div", {
              className: Job_Css$Frontend.content,
              dangerouslySetInnerHTML: {
                __html: match$1[/* requirement */12]
              }
            }));
  }
  return React.createElement("div", {
              className: "container"
            }, React.createElement("div", {
                  className: "row"
                }, React.createElement("div", {
                      className: "col-md-8"
                    }, tmp), React.createElement("div", {
                      className: "col-md-4"
                    })));
}

var Css = 0;

var make = Job;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
