// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";

function Job(Props) {
  var id = Props.id;
  return React.createElement("div", {
              className: "container"
            }, React.createElement("div", {
                  className: "page-header"
                }, React.createElement("h1", {
                      className: "page-title"
                    }, Prelude$Frontend.s("Job" + id))));
}

var make = Job;

export {
  make ,
  
}
/* react Not a pure module */
