// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var content = Emotion.css(undefined, /* :: */[
      Emotion.label("content"),
      /* :: */[
        Emotion.marginRight(/* `px */[
              25096,
              60
            ]),
        /* :: */[
          Emotion.select("p, li", /* :: */[
                Emotion.fontSize(/* `px */[
                      25096,
                      18
                    ]),
                /* :: */[
                  Emotion.fontWeight(300),
                  /* :: */[
                    Emotion.lineHeight(/* `px */[
                          25096,
                          24
                        ]),
                    /* :: */[
                      Emotion.marginBottom(/* `px */[
                            25096,
                            16
                          ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]),
          /* :: */[
            Emotion.select("ul", /* :: */[
                  Emotion.marginBottom(/* `px */[
                        25096,
                        24
                      ]),
                  /* [] */0
                ]),
            /* :: */[
              Emotion.select(".brand-sec", /* :: */[
                    Emotion.fontSize(/* `px */[
                          25096,
                          22
                        ]),
                    /* :: */[
                      Emotion.fontWeight(700),
                      /* [] */0
                    ]
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var contentWrapper = Emotion.css(undefined, /* :: */[
      Emotion.label("contentWrapper"),
      /* :: */[
        Emotion.borderBottom(/* `px */[
              25096,
              1
            ], /* solid */12956715, /* `hex */[
              5194459,
              "eee"
            ]),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                30
              ]),
          /* :: */[
            Emotion.paddingBottom(/* `px */[
                  25096,
                  30
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var postDate = Emotion.css(undefined, /* :: */[
      Emotion.label("postDate"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                12
              ]),
          /* [] */0
        ]
      ]
    ]);

var jobTitle = Emotion.css(undefined, /* :: */[
      Emotion.label("jobTitle"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                28
              ]),
          /* :: */[
            Emotion.fontWeight(700),
            /* :: */[
              Emotion.marginBottom(/* `px */[
                    25096,
                    20
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var companyName = Emotion.css(undefined, /* :: */[
      Emotion.label("companyName"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                14
              ]),
          /* :: */[
            Emotion.marginBottom(/* `px */[
                  25096,
                  20
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var tags = Emotion.css(undefined, /* :: */[
      Emotion.label("tags"),
      /* :: */[
        Emotion.marginBottom(/* `px */[
              25096,
              20
            ]),
        /* :: */[
          Emotion.borderBottom(/* `px */[
                25096,
                1
              ], /* solid */12956715, /* `hex */[
                5194459,
                "eee"
              ]),
          /* :: */[
            Emotion.paddingBottom(/* `px */[
                  25096,
                  30
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var tag = Emotion.css(undefined, /* :: */[
      Emotion.label("tag"),
      /* :: */[
        Emotion.display(/* inlineBlock */-147785676),
        /* :: */[
          Emotion.backgroundColor(/* `hex */[
                5194459,
                "0088ec"
              ]),
          /* :: */[
            Emotion.color(Emotion.Css[/* Color */11][/* white */145]),
            /* :: */[
              Emotion.padding2(/* `px */[
                    25096,
                    3
                  ], /* `px */[
                    25096,
                    10
                  ]),
              /* :: */[
                Emotion.marginRight(/* `px */[
                      25096,
                      10
                    ]),
                /* :: */[
                  Emotion.marginBottom(/* `px */[
                        25096,
                        10
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var quality = Emotion.css(undefined, /* :: */[
      Emotion.label("quality"),
      /* :: */[
        Emotion.boxShadow(/* zero */-789508312, /* zero */-789508312, /* zero */-789508312, /* `px */[
              25096,
              1
            ], undefined, /* `rgba */[
              -878128972,
              /* tuple */[
                0,
                0,
                0,
                0.16
              ]
            ]),
        /* :: */[
          Emotion.position(/* relative */903134412),
          /* :: */[
            Emotion.marginTop(/* `px */[
                  25096,
                  30
                ]),
            /* :: */[
              Emotion.marginBottom(/* `px */[
                    25096,
                    30
                  ]),
              /* :: */[
                Emotion.padding4(/* `px */[
                      25096,
                      40
                    ], /* `px */[
                      25096,
                      20
                    ], /* `px */[
                      25096,
                      20
                    ], /* `px */[
                      25096,
                      20
                    ]),
                /* :: */[
                  Emotion.textAlign(/* left */-944764921),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var letusKnow = Emotion.css(undefined, /* :: */[
      Emotion.label("letusKnow"),
      /* :: */[
        Emotion.border(/* `px */[
              25096,
              1
            ], /* solid */12956715, /* `hex */[
              5194459,
              "ccc"
            ]),
        /* :: */[
          Emotion.padding2(/* `px */[
                25096,
                10
              ], /* `px */[
                25096,
                20
              ]),
          /* :: */[
            Emotion.color(/* `hex */[
                  5194459,
                  "333"
                ]),
            /* :: */[
              Emotion.marginTop(/* `px */[
                    25096,
                    10
                  ]),
              /* :: */[
                Emotion.display(/* inlineBlock */-147785676),
                /* :: */[
                  Emotion.hover(/* :: */[
                        Emotion.textDecoration(/* none */-922086728),
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  content ,
  contentWrapper ,
  postDate ,
  jobTitle ,
  companyName ,
  tags ,
  tag ,
  quality ,
  letusKnow ,
  
}
/* content Not a pure module */
