// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var content = Emotion.css(undefined, /* :: */[
      Emotion.label("content"),
      /* :: */[
        Emotion.select("p", /* :: */[
              Emotion.fontSize(/* `px */[
                    25096,
                    16
                  ]),
              /* :: */[
                Emotion.lineHeight(/* `px */[
                      25096,
                      24
                    ]),
                /* [] */0
              ]
            ]),
        /* :: */[
          Emotion.select(".brand-sec", /* :: */[
                Emotion.fontSize(/* `px */[
                      25096,
                      24
                    ]),
                /* :: */[
                  Emotion.fontWeight(700),
                  /* [] */0
                ]
              ]),
          /* [] */0
        ]
      ]
    ]);

var postDate = Emotion.css(undefined, /* :: */[
      Emotion.label("postDate"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                12
              ]),
          /* [] */0
        ]
      ]
    ]);

var jobTitle = Emotion.css(undefined, /* :: */[
      Emotion.label("jobTitle"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                28
              ]),
          /* :: */[
            Emotion.marginBottom(/* `px */[
                  25096,
                  20
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var companyName = Emotion.css(undefined, /* :: */[
      Emotion.label("companyName"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                14
              ]),
          /* :: */[
            Emotion.marginBottom(/* `px */[
                  25096,
                  20
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var tags = Emotion.css(undefined, /* :: */[
      Emotion.label("tags"),
      /* :: */[
        Emotion.marginBottom(/* `px */[
              25096,
              30
            ]),
        /* :: */[
          Emotion.borderBottom(/* `px */[
                25096,
                1
              ], /* solid */12956715, /* `hex */[
                5194459,
                "eee"
              ]),
          /* :: */[
            Emotion.paddingBottom(/* `px */[
                  25096,
                  30
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var tag = Emotion.css(undefined, /* :: */[
      Emotion.label("tag"),
      /* :: */[
        Emotion.display(/* inlineBlock */-147785676),
        /* :: */[
          Emotion.backgroundColor(/* `hex */[
                5194459,
                "ef4f00"
              ]),
          /* :: */[
            Emotion.color(Emotion.Css[/* Color */11][/* white */145]),
            /* :: */[
              Emotion.padding2(/* `px */[
                    25096,
                    3
                  ], /* `px */[
                    25096,
                    10
                  ]),
              /* :: */[
                Emotion.marginRight(/* `px */[
                      25096,
                      10
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  content ,
  postDate ,
  jobTitle ,
  companyName ,
  tags ,
  tag ,
  
}
/* content Not a pure module */
