// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Prelude$Tripdeer from "../helpers/Prelude.bs.js";

function Jobs(Props) {
  return React.createElement("div", {
              className: "container"
            }, React.createElement("div", {
                  className: "page-header"
                }, React.createElement("h1", {
                      className: "page-title"
                    }, Prelude$Tripdeer.s("Jobs"))));
}

var make = Jobs;

export {
  make ,
  
}
/* react Not a pure module */
