// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Api$Frontend from "../helpers/Api.bs.js";
import * as Jobs_bs$Frontend from "../types/jobs_bs.bs.js";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";
import * as JobsList$Frontend from "../components/JobsList.bs.js";
import * as Jobs_Css$Frontend from "./Jobs_Css.bs.js";
import * as Atdgen_codec_runtime from "@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js";

function Jobs(Props) {
  var match = React.useState((function () {
          return /* Loading */0;
        }));
  var setJobs = match[1];
  var jobs = match[0];
  React.useEffect((function () {
          var partial_arg = Atdgen_codec_runtime.Decode[/* decode */1];
          Api$Frontend.Jobs[/* jobs */1]((function (param) {
                      return partial_arg(Jobs_bs$Frontend.read_latestJobs, param);
                    })).then((function (res) {
                    return Promise.resolve(Curry._1(setJobs, (function (param) {
                                      return /* Loaded */Block.__(0, [res]);
                                    })));
                  })).catch((function (err) {
                  return Promise.resolve(Curry._1(setJobs, (function (param) {
                                    return /* Error */Block.__(1, [err]);
                                  })));
                }));
          return undefined;
        }), ([]));
  var tmp;
  tmp = typeof jobs === "number" ? Prelude$Frontend.s("Loading...") : (
      jobs.tag ? Prelude$Frontend.s(jobs[0].toString()) : React.createElement(React.Fragment, undefined, React.createElement(JobsList$Frontend.make, {
                  jobs: jobs[0]
                }))
    );
  return React.createElement("div", {
              className: "container"
            }, React.createElement("div", {
                  className: "page-header"
                }, React.createElement("div", {
                      className: Cn.make(/* :: */[
                            "container",
                            /* :: */[
                              Jobs_Css$Frontend.jobsList,
                              /* [] */0
                            ]
                          ])
                    }, React.createElement("h1", {
                          className: "page-title"
                        }, Prelude$Frontend.s("Find a Jobs")), tmp)));
}

var Css = 0;

var make = Jobs;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
