// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var jobsList = Emotion.css(undefined, /* :: */[
      Emotion.label("jobsList"),
      /* :: */[
        Emotion.marginBottom(/* `px */[
              25096,
              60
            ]),
        /* [] */0
      ]
    ]);

var title = Emotion.css(undefined, /* :: */[
      Emotion.label("title"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              24
            ]),
        /* :: */[
          Emotion.fontWeight(700),
          /* :: */[
            Emotion.marginBottom(/* `px */[
                  25096,
                  60
                ]),
            /* :: */[
              Emotion.marginTop(/* `px */[
                    25096,
                    20
                  ]),
              /* :: */[
                Emotion.display(/* block */888960333),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  jobsList ,
  title ,
  
}
/* jobsList Not a pure module */
