// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as JobT$Frontend from "../types/JobT.bs.js";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";
import * as Jobs_Css$Frontend from "./Jobs_Css.bs.js";
import * as FormErrorMsg$Frontend from "./FormErrorMsg.bs.js";
import * as Formality__PublicHelpers from "re-formality/src/Formality__PublicHelpers.bs.js";

function NewJob(Props) {
  var form = Curry._2(JobT$Frontend.FormHook[/* useForm */2], /* record */[
        /* title */"",
        /* category */"",
        /* type_ */"fullTime",
        /* apply */"",
        /* description */""
      ], (function (state, form) {
          console.log("Submitted with:", state);
          setTimeout((function (param) {
                  Curry._1(form[/* notifyOnSuccess */0], undefined);
                  setTimeout(form[/* reset */2], 3000);
                  return /* () */0;
                }), 500);
          return /* () */0;
        }));
  var partial_arg = form[/* submit */8];
  var partial_arg$1 = Formality__PublicHelpers.Dom[/* preventDefault */0];
  var match = form[/* submitting */5];
  return React.createElement("div", {
              className: "container"
            }, React.createElement("div", {
                  className: "page-header"
                }, React.createElement("div", {
                      className: Cn.make(/* :: */[
                            "container",
                            /* :: */[
                              Jobs_Css$Frontend.jobsList,
                              /* [] */0
                            ]
                          ])
                    }, React.createElement("h1", {
                          className: "page-title text-center"
                        }, React.createElement("strong", undefined, Prelude$Frontend.s("Posting a Jobs has been much easier with ParentalJobs"))), React.createElement("p", {
                          className: "text-center"
                        }, Prelude$Frontend.s("For every job you posted, with pledge to be parents friendly, we contribute 5% to foundations to need help.")), React.createElement("form", {
                          className: "mt-8",
                          onSubmit: (function (param) {
                              return partial_arg$1(partial_arg, param);
                            })
                        }, React.createElement("h4", undefined, Prelude$Frontend.s("First, tell us about the position")), React.createElement("div", {
                              className: "mt-5 form-group"
                            }, React.createElement("label", undefined, React.createElement("strong", undefined, Prelude$Frontend.s("Job title"))), React.createElement("input", {
                                  className: "form-control",
                                  disabled: form[/* submitting */5],
                                  value: form[/* state */0][/* title */0],
                                  onBlur: (function (param) {
                                      return Curry._1(form[/* blur */7], /* Title */0);
                                    }),
                                  onChange: (function ($$event) {
                                      return Curry._2(form[/* change */6], /* Title */0, Curry._2(JobT$Frontend.Form[/* Title_F */0][/* update */0], form[/* state */0], $$event.target.value));
                                    })
                                }), React.createElement(FormErrorMsg$Frontend.make, {
                                  type_: Curry._1(form[/* result */2], /* Title */0)
                                })), React.createElement("div", {
                              className: "mt-5 form-group"
                            }, React.createElement("label", undefined, React.createElement("strong", undefined, Prelude$Frontend.s("Category"))), React.createElement("input", {
                                  className: "form-control",
                                  disabled: form[/* submitting */5],
                                  value: form[/* state */0][/* category */1],
                                  onBlur: (function (param) {
                                      return Curry._1(form[/* blur */7], /* Category */1);
                                    }),
                                  onChange: (function ($$event) {
                                      return Curry._2(form[/* change */6], /* Category */1, Curry._2(JobT$Frontend.Form[/* Category_F */1][/* update */0], form[/* state */0], $$event.target.value));
                                    })
                                }), React.createElement(FormErrorMsg$Frontend.make, {
                                  type_: Curry._1(form[/* result */2], /* Category */1)
                                })), React.createElement("div", {
                              className: "mt-5 form-group"
                            }, React.createElement("div", {
                                  className: "form-label"
                                }, React.createElement("strong", undefined, Prelude$Frontend.s("Job type"))), React.createElement("label", {
                                  className: "custom-control custom-radio custom-control-inline"
                                }, React.createElement("input", {
                                      className: "custom-control-input",
                                      checked: form[/* state */0][/* type_ */2] === "fullTime",
                                      name: "type",
                                      type: "radio",
                                      value: "fullTime",
                                      onChange: (function ($$event) {
                                          return Curry._2(form[/* change */6], /* Type */2, Curry._2(JobT$Frontend.Form[/* Category_F */1][/* update */0], form[/* state */0], $$event.target.value));
                                        })
                                    }), React.createElement("span", {
                                      className: "custom-control-label"
                                    }, Prelude$Frontend.s("Full time"))), React.createElement("label", {
                                  className: "custom-control custom-radio custom-control-inline"
                                }, React.createElement("input", {
                                      className: "custom-control-input",
                                      checked: form[/* state */0][/* type_ */2] === "contact",
                                      name: "type",
                                      type: "radio",
                                      value: "Contact",
                                      onChange: (function ($$event) {
                                          return Curry._2(form[/* change */6], /* Type */2, Curry._2(JobT$Frontend.Form[/* Category_F */1][/* update */0], form[/* state */0], $$event.target.value));
                                        })
                                    }), React.createElement("span", {
                                      className: "custom-control-label"
                                    }, Prelude$Frontend.s("Contact")))), React.createElement("div", {
                              className: "mt-5 form-group"
                            }, React.createElement("label", undefined, React.createElement("strong", undefined, Prelude$Frontend.s("Apply url"))), React.createElement("input", {
                                  className: "form-control",
                                  disabled: form[/* submitting */5],
                                  value: form[/* state */0][/* apply */3],
                                  onBlur: (function (param) {
                                      return Curry._1(form[/* blur */7], /* Apply */3);
                                    }),
                                  onChange: (function ($$event) {
                                      return Curry._2(form[/* change */6], /* Apply */3, Curry._2(JobT$Frontend.Form[/* Apply_F */2][/* update */0], form[/* state */0], $$event.target.value));
                                    })
                                }), React.createElement(FormErrorMsg$Frontend.make, {
                                  type_: Curry._1(form[/* result */2], /* Apply */3)
                                })), React.createElement("div", {
                              className: "mt-5 form-group"
                            }, React.createElement("label", undefined, React.createElement("strong", undefined, Prelude$Frontend.s("Job description"))), React.createElement("textarea", {
                                  className: "form-control",
                                  disabled: form[/* submitting */5],
                                  rows: 5,
                                  value: form[/* state */0][/* description */4],
                                  onBlur: (function (param) {
                                      return Curry._1(form[/* blur */7], /* Description */7);
                                    }),
                                  onChange: (function ($$event) {
                                      return Curry._2(form[/* change */6], /* Description */7, Curry._2(JobT$Frontend.Form[/* Description_F */3][/* update */0], form[/* state */0], $$event.target.value));
                                    })
                                }), React.createElement(FormErrorMsg$Frontend.make, {
                                  type_: Curry._1(form[/* result */2], /* Apply */3)
                                })), React.createElement("button", {
                              className: "btn btn-primary",
                              disabled: form[/* submitting */5]
                            }, match ? "Submitting..." : "Submit")))));
}

var Css = 0;

var make = NewJob;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
