// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* :: */[
        Emotion.textAlign(/* center */98248149),
        /* [] */0
      ]
    ]);

export {
  container ,
  
}
/* container Not a pure module */
