// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var hexRed = "ef4f00";

var hexRedHovered = "ef2f00";

var button = Emotion.css(undefined, /* :: */[
      Emotion.label("button"),
      /* :: */[
        Emotion.borderStyle(/* none */-922086728),
        /* :: */[
          Emotion.padding2(/* `px */[
                25096,
                10
              ], /* `px */[
                25096,
                20
              ]),
          /* :: */[
            Emotion.backgroundColor(/* `hex */[
                  5194459,
                  hexRed
                ]),
            /* :: */[
              Emotion.color(Emotion.Css[/* Color */11][/* white */145]),
              /* :: */[
                Emotion.fontWeight(700),
                /* :: */[
                  Emotion.hover(/* :: */[
                        Emotion.backgroundColor(/* `hex */[
                              5194459,
                              hexRedHovered
                            ]),
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  hexRed ,
  hexRedHovered ,
  button ,
  
}
/* button Not a pure module */
