// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";
import * as ApplyBtn_Css$Frontend from "./ApplyBtn_Css.bs.js";

function ApplyBtn(Props) {
  var className = Props.className;
  return React.createElement("button", {
              className: Cn.make(/* :: */[
                    ApplyBtn_Css$Frontend.button,
                    /* :: */[
                      Cn.unpack(className),
                      /* [] */0
                    ]
                  ])
            }, Prelude$Frontend.s("Apply for this position"));
}

var Css = 0;

var make = ApplyBtn;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
