// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";
import * as $$String from "bs-platform/lib/es6/string.js";
import * as Js_math from "bs-platform/lib/es6/js_math.js";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_string from "bs-platform/lib/es6/caml_string.js";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";
import * as Avatar_Css$Frontend from "./Avatar_Css.bs.js";

function randomBgColor(param) {
  var colors = /* :: */[
    "#f74b4b",
    /* :: */[
      "#1988ff",
      /* :: */[
        "#f7bc4b",
        /* :: */[
          "#e64bf7",
          /* :: */[
            "#29d400",
            /* :: */[
              "#d47700",
              /* :: */[
                "#ce5baf",
                /* :: */[
                  "#5bce8f",
                  /* :: */[
                    "#5a4ba7",
                    /* :: */[
                      "#d26666",
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ];
  return Belt_Option.getWithDefault(Belt_List.get(colors, Js_math.random_int(0, Belt_List.length(colors)) - 1 | 0), "#f74b4b");
}

function Avatar(Props) {
  var className = Props.className;
  var company = Props.company;
  var logo = Props.logo;
  return React.createElement("span", {
              className: Cn.make(/* :: */[
                    Avatar_Css$Frontend.avatar,
                    /* :: */[
                      Cn.unpack(className),
                      /* [] */0
                    ]
                  ]),
              style: {
                backgroundColor: randomBgColor(/* () */0)
              }
            }, logo !== undefined ? React.createElement("img", {
                    alt: company,
                    src: logo
                  }) : React.createElement("span", {
                    className: Avatar_Css$Frontend.name
                  }, Prelude$Frontend.s($$String.make(1, Caml_string.get(company, 0)))));
}

var Css = 0;

var make = Avatar;

export {
  Css ,
  randomBgColor ,
  make ,
  
}
/* react Not a pure module */
