// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var avatar = Emotion.css(undefined, /* :: */[
      Emotion.label("avatar"),
      /* :: */[
        Emotion.width(/* `px */[
              25096,
              60
            ]),
        /* :: */[
          Emotion.height(/* `px */[
                25096,
                60
              ]),
          /* :: */[
            Emotion.border(/* `px */[
                  25096,
                  3
                ], /* solid */12956715, Emotion.Css[/* Color */11][/* white */145]),
            /* :: */[
              Emotion.backgroundColor(/* `hex */[
                    5194459,
                    "f3f3f3"
                  ]),
              /* :: */[
                Emotion.borderRadius(/* `pct */[
                      5591841,
                      50
                    ]),
                /* :: */[
                  Emotion.color(Emotion.Css[/* Color */11][/* white */145]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var name = Emotion.css(undefined, /* :: */[
      Emotion.label("name"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              32
            ]),
        /* :: */[
          Emotion.fontWeight(700),
          /* :: */[
            Emotion.display(/* flex */-1010954439),
            /* :: */[
              Emotion.width(/* `pct */[
                    5591841,
                    100
                  ]),
              /* :: */[
                Emotion.height(/* `pct */[
                      5591841,
                      100
                    ]),
                /* :: */[
                  Emotion.alignItems(/* center */98248149),
                  /* :: */[
                    Emotion.justifyContent(/* center */98248149),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  avatar ,
  name ,
  
}
/* avatar Not a pure module */
