// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Avatar$Frontend from "./Avatar.bs.js";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";
import * as ApplyBtn$Frontend from "./ApplyBtn.bs.js";
import * as CompanyInfo_Css$Frontend from "./CompanyInfo_Css.bs.js";

function CompanyInfo(Props) {
  var className = Props.className;
  var address = Props.address;
  var company = Props.company;
  var logo = Props.logo;
  var tmp = {
    className: CompanyInfo_Css$Frontend.avatar,
    company: company
  };
  if (logo !== undefined) {
    tmp.logo = Caml_option.valFromOption(logo);
  }
  return React.createElement("div", {
              className: Cn.make(/* :: */[
                    CompanyInfo_Css$Frontend.info,
                    /* :: */[
                      Cn.unpack(className),
                      /* [] */0
                    ]
                  ])
            }, React.createElement(Avatar$Frontend.make, tmp), React.createElement("h3", {
                  className: CompanyInfo_Css$Frontend.company
                }, Prelude$Frontend.s(company)), address !== "" ? React.createElement("p", {
                    className: CompanyInfo_Css$Frontend.address
                  }, Prelude$Frontend.s(address)) : null, React.createElement(ApplyBtn$Frontend.make, {
                  className: CompanyInfo_Css$Frontend.button
                }));
}

var Css = 0;

var make = CompanyInfo;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
