// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var info = Emotion.css(undefined, /* :: */[
      Emotion.label("info"),
      /* :: */[
        Emotion.boxShadow(/* zero */-789508312, /* zero */-789508312, /* zero */-789508312, /* `px */[
              25096,
              1
            ], undefined, /* `rgba */[
              -878128972,
              /* tuple */[
                0,
                0,
                0,
                0.16
              ]
            ]),
        /* :: */[
          Emotion.position(/* relative */903134412),
          /* :: */[
            Emotion.marginTop(/* `px */[
                  25096,
                  30
                ]),
            /* :: */[
              Emotion.padding4(/* `px */[
                    25096,
                    40
                  ], /* `px */[
                    25096,
                    20
                  ], /* `px */[
                    25096,
                    20
                  ], /* `px */[
                    25096,
                    20
                  ]),
              /* :: */[
                Emotion.textAlign(/* center */98248149),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var company = Emotion.css(undefined, /* :: */[
      Emotion.label("company"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              16
            ]),
        /* :: */[
          Emotion.fontWeight(700),
          /* [] */0
        ]
      ]
    ]);

var address = Emotion.css(undefined, /* :: */[
      Emotion.label("address"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              16
            ]),
        /* [] */0
      ]
    ]);

var button = Emotion.css(undefined, /* :: */[
      Emotion.label("button"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.width(/* `pct */[
                5591841,
                100
              ]),
          /* [] */0
        ]
      ]
    ]);

var avatar = Emotion.css(undefined, /* :: */[
      Emotion.label("avatar"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.position(/* absolute */-1013592457),
          /* :: */[
            Emotion.left(/* `pct */[
                  5591841,
                  50
                ]),
            /* :: */[
              Emotion.marginLeft(/* `px */[
                    25096,
                    -30
                  ]),
              /* :: */[
                Emotion.top(/* `px */[
                      25096,
                      -30
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  info ,
  company ,
  address ,
  button ,
  avatar ,
  
}
/* info Not a pure module */
