// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Prelude$Tripdeer from "../helpers/Prelude.bs.js";

function Footer(Props) {
  return React.createElement("footer", {
              className: "footer"
            }, React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row align-items-center flex-row-reverse"
                    }, React.createElement("div", {
                          className: "col-12 col-lg-auto mt-3 mt-lg-0 text-center"
                        }, Prelude$Tripdeer.s("Copyright 2019 ParentalJobs")))));
}

var make = Footer;

export {
  make ,
  
}
/* react Not a pure module */
