// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var hexRed = "ef4f00";

var topFooter = Emotion.css(undefined, /* :: */[
      Emotion.label("topFooter"),
      /* :: */[
        Emotion.important(Emotion.backgroundColor(/* `hex */[
                  5194459,
                  "333"
                ])),
        /* :: */[
          Emotion.important(Emotion.padding2(/* `px */[
                    25096,
                    60
                  ], /* zero */-789508312)),
          /* [] */0
        ]
      ]
    ]);

var title = Emotion.css(undefined, /* :: */[
      Emotion.label("title"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              22
            ]),
        /* :: */[
          Emotion.fontWeight(900),
          /* :: */[
            Emotion.textTransform(/* uppercase */-415330030),
            /* [] */0
          ]
        ]
      ]
    ]);

var button = Emotion.css(undefined, /* :: */[
      Emotion.label("button"),
      /* :: */[
        Emotion.display(/* inlineBlock */-147785676),
        /* :: */[
          Emotion.borderStyle(/* none */-922086728),
          /* :: */[
            Emotion.padding2(/* `px */[
                  25096,
                  10
                ], /* `px */[
                  25096,
                  20
                ]),
            /* :: */[
              Emotion.backgroundColor(/* `hex */[
                    5194459,
                    hexRed
                  ]),
              /* :: */[
                Emotion.color(Emotion.Css[/* Color */11][/* white */145]),
                /* :: */[
                  Emotion.fontWeight(700),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  hexRed ,
  topFooter ,
  title ,
  button ,
  
}
/* topFooter Not a pure module */
