// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Prelude$Tripdeer from "../helpers/Prelude.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function Header(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "header py-4"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: "d-flex"
                        }, React.createElement("a", {
                              className: "header-brand",
                              href: "/",
                              onClick: (function ($$event) {
                                  var $$event$1 = $$event;
                                  var path = "/";
                                  $$event$1.preventDefault();
                                  return ReasonReactRouter.push(path);
                                })
                            }, Prelude$Tripdeer.s("ParentalJobs"))))));
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
