// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var brand = Emotion.css(undefined, /* :: */[
      Emotion.label("brand"),
      /* :: */[
        Emotion.important(Emotion.color(/* `hex */[
                  5194459,
                  "ef4f0b"
                ])),
        /* :: */[
          Emotion.textTransform(/* uppercase */-415330030),
          /* :: */[
            Emotion.important(Emotion.fontWeight(900)),
            /* [] */0
          ]
        ]
      ]
    ]);

var navLink = Emotion.css(undefined, /* :: */[
      Emotion.label("navLink"),
      /* :: */[
        Emotion.color(/* `hex */[
              5194459,
              "333"
            ]),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                18
              ]),
          /* :: */[
            Emotion.hover(/* :: */[
                  Emotion.color(/* `hex */[
                        5194459,
                        "ef4f00"
                      ]),
                  /* [] */0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

export {
  brand ,
  navLink ,
  
}
/* brand Not a pure module */
