// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var jobsListWrapper = Emotion.css(undefined, /* :: */[
      Emotion.label("jobsListWrapper"),
      /* :: */[
        Emotion.paddingLeft(/* zero */-789508312),
        /* [] */0
      ]
    ]);

var job = Emotion.css(undefined, /* :: */[
      Emotion.label("job"),
      /* :: */[
        Emotion.backgroundColor(/* `rgba */[
              -878128972,
              /* tuple */[
                3,
                3,
                3,
                0.02
              ]
            ]),
        /* :: */[
          Emotion.margin(/* zero */-789508312),
          /* :: */[
            Emotion.listStyleType(/* none */-922086728),
            /* :: */[
              Emotion.padding(/* `px */[
                    25096,
                    20
                  ]),
              /* :: */[
                Emotion.marginBottom(/* `px */[
                      25096,
                      20
                    ]),
                /* :: */[
                  Emotion.borderLeft(/* `px */[
                        25096,
                        5
                      ], /* solid */12956715, /* `hex */[
                        5194459,
                        "d4d4d4"
                      ]),
                  /* :: */[
                    Emotion.display(/* flex */-1010954439),
                    /* :: */[
                      Emotion.flexWrap(/* wrap */-822134326),
                      /* :: */[
                        Emotion.alignItems(/* center */98248149),
                        /* :: */[
                          Emotion.position(/* relative */903134412),
                          /* :: */[
                            Emotion.select("div:first-of-type", /* :: */[
                                  Emotion.flex(/* `some */[
                                        -866639116,
                                        /* tuple */[
                                          1,
                                          1,
                                          /* auto */-1065951377
                                        ]
                                      ]),
                                  /* [] */0
                                ]),
                            /* :: */[
                              Emotion.hover(/* :: */[
                                    Emotion.backgroundColor(/* `rgba */[
                                          -878128972,
                                          /* tuple */[
                                            3,
                                            3,
                                            3,
                                            0.04
                                          ]
                                        ]),
                                    /* :: */[
                                      Emotion.cursor(/* pointer */-786317123),
                                      /* [] */0
                                    ]
                                  ]),
                              /* :: */[
                                Emotion.media("(max-width: 768px)", /* :: */[
                                      Emotion.paddingTop(/* `px */[
                                            25096,
                                            40
                                          ]),
                                      /* :: */[
                                        Emotion.marginBottom(/* `px */[
                                              25096,
                                              60
                                            ]),
                                        /* [] */0
                                      ]
                                    ]),
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var avatar = Emotion.css(undefined, /* :: */[
      Emotion.label("avatar"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.position(/* absolute */-1013592457),
          /* :: */[
            Emotion.right(/* `px */[
                  25096,
                  -30
                ]),
            /* :: */[
              Emotion.media("(max-width: 768px)", /* :: */[
                    Emotion.right(/* `pct */[
                          5591841,
                          50
                        ]),
                    /* :: */[
                      Emotion.marginRight(/* `px */[
                            25096,
                            -30
                          ]),
                      /* :: */[
                        Emotion.top(/* `px */[
                              25096,
                              -30
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var parentFriendlyjob = Emotion.css(undefined, /* :: */[
      Emotion.label("parentFriendlyjob"),
      /* :: */[
        Emotion.backgroundColor(/* `rgba */[
              -878128972,
              /* tuple */[
                255,
                137,
                32,
                0.18
              ]
            ]),
        /* [] */0
      ]
    ]);

var company = Emotion.css(undefined, /* :: */[
      Emotion.label("company"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                16
              ]),
          /* :: */[
            Emotion.marginBottom(/* `px */[
                  25096,
                  8
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var jobTitle = Emotion.css(undefined, /* :: */[
      Emotion.label("jobTitle"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                24
              ]),
          /* :: */[
            Emotion.marginBottom(/* `px */[
                  25096,
                  12
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var category = Emotion.css(undefined, /* :: */[
      Emotion.label("category"),
      /* :: */[
        Emotion.fontStyle(/* normal */812216871),
        /* [] */0
      ]
    ]);

var employmentType = Emotion.css(undefined, /* :: */[
      Emotion.label("employmentType"),
      /* :: */[
        Emotion.marginLeft(/* auto */-1065951377),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                16
              ]),
          /* :: */[
            Emotion.fontWeight(700),
            /* :: */[
              Emotion.marginRight(/* `px */[
                    25096,
                    50
                  ]),
              /* :: */[
                Emotion.media("(max-width: 768px)", /* :: */[
                      Emotion.display(/* block */888960333),
                      /* :: */[
                        Emotion.marginTop(/* `px */[
                              25096,
                              20
                            ]),
                        /* :: */[
                          Emotion.width(/* `pct */[
                                5591841,
                                100
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  jobsListWrapper ,
  job ,
  avatar ,
  parentFriendlyjob ,
  company ,
  jobTitle ,
  category ,
  employmentType ,
  
}
/* jobsListWrapper Not a pure module */
