// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Avatar$Frontend from "./Avatar.bs.js";
import * as Prelude$Frontend from "../helpers/Prelude.bs.js";
import * as JobsList_Css$Frontend from "./JobsList_Css.bs.js";

function JobsList(Props) {
  var jobs = Props.jobs;
  return React.createElement("ul", {
              className: JobsList_Css$Frontend.jobsListWrapper
            }, Prelude$Frontend.RR[/* list */9](Belt_List.map(jobs, (function (param) {
                        var id = param[/* _id */0];
                        var company = param[/* company */1];
                        return React.createElement("li", {
                                    key: id,
                                    className: JobsList_Css$Frontend.job,
                                    onClick: (function ($$event) {
                                        return Prelude$Frontend.linkTo("/job/" + (String(id) + ""), $$event);
                                      })
                                  }, React.createElement(Avatar$Frontend.make, {
                                        className: JobsList_Css$Frontend.avatar,
                                        company: company
                                      }), React.createElement("div", undefined, React.createElement("span", {
                                            className: JobsList_Css$Frontend.company
                                          }, Prelude$Frontend.s(company)), React.createElement("h3", {
                                            className: JobsList_Css$Frontend.jobTitle
                                          }, Prelude$Frontend.s(param[/* jobTitle */2])), React.createElement("cite", {
                                            className: JobsList_Css$Frontend.category
                                          }, React.createElement("span", undefined, Prelude$Frontend.s(param[/* jobCategories */6])))), React.createElement("div", {
                                        className: JobsList_Css$Frontend.employmentType
                                      }, React.createElement("span", undefined, Prelude$Frontend.s(param[/* employmentType */3]))));
                      }))));
}

var Css = 0;

var make = JobsList;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
