// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Atdgen_codec_runtime from "@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js";

var partial_arg = Atdgen_codec_runtime.Encode[/* string */3];

var partial_arg$1 = Atdgen_codec_runtime.Encode[/* option_as_constr */23];

function write__1(param) {
  return partial_arg$1(partial_arg, param);
}

var read__1 = Atdgen_codec_runtime.Decode[/* option_as_constr */25](Atdgen_codec_runtime.Decode[/* string */7]);

var write_salary = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */[
                    Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "salaryFrom", t[/* salaryFrom */0]),
                    /* :: */[
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "salaryTo", t[/* salaryTo */1]),
                      /* :: */[
                        Atdgen_codec_runtime.Encode[/* field */12](undefined, write__1, "salaryType", t[/* salaryType */2]),
                        /* [] */0
                      ]
                    ]
                  ]);
      }));

var read_salary = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$3 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$4 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */[
                /* salaryFrom */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$1("salaryFrom", partial_arg, param);
                      }), json),
                /* salaryTo */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$3("salaryTo", partial_arg$2, param);
                      }), json),
                /* salaryType */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$4("salaryType", read__1, param);
                      }), json)
              ];
      }));

var write_job = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */[
                    Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "company", t[/* company */0]),
                    /* :: */[
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "jobTitle", t[/* jobTitle */1]),
                      /* :: */[
                        Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "jobId", t[/* jobId */2]),
                        /* :: */[
                          Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "address", t[/* address */3]),
                          /* :: */[
                            Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "employmentType", t[/* employmentType */4]),
                            /* :: */[
                              Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "seniority", t[/* seniority */5]),
                              /* :: */[
                                Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "minExperience", t[/* minExperience */6]),
                                /* :: */[
                                  Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "jobCategories", t[/* jobCategories */7]),
                                  /* :: */[
                                    Atdgen_codec_runtime.Encode[/* field */12](undefined, write_salary, "salary", t[/* salary */8]),
                                    /* :: */[
                                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "postedOn", t[/* postedOn */9]),
                                      /* :: */[
                                        Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "jobDescription", t[/* jobDescription */10]),
                                        /* :: */[
                                          Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "requirement", t[/* requirement */11]),
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]);
      }));

var read_job = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$3 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$4 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$5 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$6 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$7 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$8 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$9 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$10 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$11 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$12 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$13 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$14 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$15 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$16 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$17 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$18 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$19 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$20 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$21 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$22 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */[
                /* company */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$1("company", partial_arg, param);
                      }), json),
                /* jobTitle */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$3("jobTitle", partial_arg$2, param);
                      }), json),
                /* jobId */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$5("jobId", partial_arg$4, param);
                      }), json),
                /* address */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$7("address", partial_arg$6, param);
                      }), json),
                /* employmentType */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$9("employmentType", partial_arg$8, param);
                      }), json),
                /* seniority */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$11("seniority", partial_arg$10, param);
                      }), json),
                /* minExperience */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$13("minExperience", partial_arg$12, param);
                      }), json),
                /* jobCategories */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$15("jobCategories", partial_arg$14, param);
                      }), json),
                /* salary */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$16("salary", read_salary, param);
                      }), json),
                /* postedOn */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$18("postedOn", partial_arg$17, param);
                      }), json),
                /* jobDescription */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$20("jobDescription", partial_arg$19, param);
                      }), json),
                /* requirement */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$22("requirement", partial_arg$21, param);
                      }), json)
              ];
      }));

var partial_arg$2 = Atdgen_codec_runtime.Encode[/* list */8];

function write__2(param) {
  return partial_arg$2(write_job, param);
}

var partial_arg$3 = Atdgen_codec_runtime.Decode[/* list */11];

function read__2(param) {
  return partial_arg$3(read_job, param);
}

var read_jobs = read__2;

var write_jobs = write__2;

export {
  read_salary ,
  write_salary ,
  read_job ,
  write_job ,
  read_jobs ,
  write_jobs ,
  
}
/* read__1 Not a pure module */
