// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Formality__Form from "re-formality/src/Formality__Form.bs.js";

function update(state, value) {
  return /* record */[
          /* title */value,
          /* category */state[/* category */1],
          /* type_ */state[/* type_ */2],
          /* apply */state[/* apply */3],
          /* description */state[/* description */4]
        ];
}

function validator_003(param) {
  if (param[/* title */0] === "") {
    return /* Error */Block.__(1, ["Please add a job title"]);
  } else {
    return /* Ok */Block.__(0, [/* Valid */0]);
  }
}

var validator = /* record */[
  /* field : Title */0,
  /* strategy : OnFirstBlur */0,
  /* dependents */undefined,
  validator_003
];

var Title_F = /* module */[
  /* update */update,
  /* validator */validator
];

function update$1(state, value) {
  return /* record */[
          /* title */state[/* title */0],
          /* category */value,
          /* type_ */state[/* type_ */2],
          /* apply */state[/* apply */3],
          /* description */state[/* description */4]
        ];
}

function validator_003$1(param) {
  if (param[/* category */1] === "") {
    return /* Error */Block.__(1, ["Please choose a category"]);
  } else {
    return /* Ok */Block.__(0, [/* Valid */0]);
  }
}

var validator$1 = /* record */[
  /* field : Category */1,
  /* strategy : OnFirstBlur */0,
  /* dependents */undefined,
  validator_003$1
];

var Category_F = /* module */[
  /* update */update$1,
  /* validator */validator$1
];

function update$2(state, value) {
  return /* record */[
          /* title */state[/* title */0],
          /* category */state[/* category */1],
          /* type_ */state[/* type_ */2],
          /* apply */value,
          /* description */state[/* description */4]
        ];
}

function validator_003$2(param) {
  if (param[/* apply */3] === "") {
    return /* Error */Block.__(1, ["Please enter your apply url or email address"]);
  } else {
    return /* Ok */Block.__(0, [/* Valid */0]);
  }
}

var validator$2 = /* record */[
  /* field : Apply */3,
  /* strategy : OnFirstBlur */0,
  /* dependents */undefined,
  validator_003$2
];

var Apply_F = /* module */[
  /* update */update$2,
  /* validator */validator$2
];

function update$3(state, value) {
  return /* record */[
          /* title */state[/* title */0],
          /* category */state[/* category */1],
          /* type_ */state[/* type_ */2],
          /* apply */state[/* apply */3],
          /* description */value
        ];
}

function validator_003$3(param) {
  if (param[/* description */4] === "") {
    return /* Error */Block.__(1, ["Please enter some descriptions"]);
  } else {
    return /* Ok */Block.__(0, [/* Valid */0]);
  }
}

var validator$3 = /* record */[
  /* field : Description */7,
  /* strategy : OnFirstBlur */0,
  /* dependents */undefined,
  validator_003$3
];

var Description_F = /* module */[
  /* update */update$3,
  /* validator */validator$3
];

var validators_001 = /* :: */[
  validator,
  /* :: */[
    validator$2,
    /* [] */0
  ]
];

var validators = /* :: */[
  validator$1,
  validators_001
];

var Form = /* module */[
  /* Title_F */Title_F,
  /* Category_F */Category_F,
  /* Apply_F */Apply_F,
  /* Description_F */Description_F,
  /* validators */validators
];

var FormHook = Formality__Form.Make([validators]);

export {
  Form ,
  FormHook ,
  
}
/* FormHook Not a pure module */
